name: cd

on:
  push:
    branches: [main]

jobs:
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install Poetry
          run: pipx install poetry

        - name: Install dependencies
          run: poetry install

        - name: Install pip
          run: python -m pip install --upgrade pip
    
        - name: Install semantic-release
          run: python3 -m pip install python-semantic-release

        - name: Semantic Release
          env: 
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            python update_version.py
            poetry build
            semantic-release publish
